#!/usr/bin/env python3
"""Round-by-round stream as a structured TABLE — every event on its own row.

Unlike the free-text listing, the payload is broken into proper columns, so the result
can go into a spreadsheet or straight into the supplementary material.

  seq | round | mode | n_act | decided_by | type | attack | n_flags | k_votes | nodes

`nodes` holds whichever node list the event type carries (failed / recovered / source),
prefixed so the meaning is never ambiguous.

  python scripts/round_by_round_table.py results/events_availability.jsonl
Out: results/table_<stem>.csv and results/table_<stem>.tex (longtable, supplementary-ready)
"""
import argparse
import csv
import json
import os
from collections import Counter

COLS = ["seq", "round", "mode", "n_active", "decided_by", "type",
        "attack", "n_flags", "k_votes", "nodes", "window_truth"]

# window_truth is ORACLE information: it comes from the scenario (via the manifest),
# NOT from the event. A deployed IDS cannot know whether a window held attack traffic —
# that is why it is not, and must not be, a field of the event schema.
TRUTH = {"benign_only": "benign (any alarm here is a FALSE POSITIVE)",
         "with_attack": "contains attack",
         "all": "mixed"}


def nodes_cell(e):
    t = e["type"]
    if t == "node_failure":
        return "failed=" + ",".join(map(str, e.get("failed_nodes", [])))
    if t == "node_recovery":
        return "recovered=" + ",".join(map(str, e.get("recovered_nodes", [])))
    if t == "node_isolated":
        return f"source={e.get('source_node')}"
    if t == "architecture_change":
        return f"{e.get('from_mode')}->{e.get('to_mode')}"
    if e.get("source_node") is not None:
        return f"source={e['source_node']}"
    return ""


def row(e, truth=""):
    return {"window_truth": truth if e["type"] == "intrusion_detected" else "",
            "seq": e["seq"], "round": e["round"], "mode": e.get("mode", ""),
            "n_active": e.get("n_active", ""), "decided_by": e.get("decided_by") or "",
            "type": e["type"], "attack": e.get("attack") or "",
            "n_flags": e.get("n_flags", ""), "k_votes": e.get("k_votes", ""),
            "nodes": nodes_cell(e)}


TEX_HEAD = r"""% Generated by scripts/round_by_round_table.py -- do not edit by hand.
% Requires: \usepackage{longtable,booktabs}
\begin{longtable}{@{}rrllllrrl@{}}
\caption{@@CAPTION@@}\label{tab:@@LABEL@@}\\
\toprule
seq & round & mode & $n_{act}$ & decided by & type & $n_{flags}$ & $k_{votes}$ & nodes / attack \\
\midrule
\endfirsthead
\multicolumn{9}{@{}l}{\small\itshape (continued)}\\
\toprule
seq & round & mode & $n_{act}$ & decided by & type & $n_{flags}$ & $k_{votes}$ & nodes / attack \\
\midrule
\endhead
\midrule \multicolumn{9}{r@{}}{\small\itshape continues on the next page}\\
\endfoot
\bottomrule
\endlastfoot
"""


def tex_escape(s):
    return str(s).replace("_", r"\_").replace("&", r"\&").replace("->", r"$\to$")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("stream")
    ap.add_argument("--caption", default=None)
    a = ap.parse_args()
    evs = [json.loads(l) for l in open(a.stream, encoding="utf-8")]
    stem = os.path.splitext(os.path.basename(a.stream))[0].replace("events_", "")
    # oracle column: the scenario's stream selector, read from the provenance manifest
    selector, truth = None, ""
    man_path = f"results/manifest_{stem}.json"
    if os.path.exists(man_path):
        selector = json.load(open(man_path, encoding="utf-8"))["stream"]["selector"]
        truth = TRUTH.get(selector, selector)
    else:
        print(f"WARNING: {man_path} missing — window_truth left blank "
              f"(regenerate with scripts/scenario_events.py)")
    rows = [row(e, truth) for e in evs]
    os.makedirs("results", exist_ok=True)

    csv_path = f"results/table_{stem}.csv"
    with open(csv_path, "w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=COLS)
        w.writeheader()
        w.writerows(rows)

    span = max(e["round"] for e in evs) + 1
    types = dict(Counter(e["type"] for e in evs))
    dec = dict(Counter(e.get("decided_by") for e in evs))
    fmt = lambda d: ", ".join(f"{v} {tex_escape(k)}" for k, v in sorted(d.items(), key=lambda x: -x[1])
                              if k is not None)
    n_auto, n_mon = dec.get("autonomous", 0), dec.get("monitor", 0)
    caption = a.caption or (
        f"Round-by-round event stream ({tex_escape(stem)}): every event explicit. "
        f"{len(evs)} events over {span} rounds of 1\\,s "
        f"($\\approx$4{{,}}673 samples each at 0.214\\,ms). "
        f"Events: {fmt(types)}. "
        f"Actions: {n_auto} autonomous, {n_mon} monitor-commanded "
        f"(observations carry no \\texttt{{decided\\_by}}). "
        + (f"Stream \\texttt{{{tex_escape(selector)}}}: "
           + ("the windows hold NO attack sample, so every alarm below is a false "
              "positive --- this is the false-positive baseline the monitor must filter. "
              if selector == "benign_only" else
              "every window holds attack traffic. ")
           + "The last column is ORACLE information from the scenario, not an event "
             "field: a deployed IDS cannot know it." if selector else ""))
    tex_path = f"results/table_{stem}.tex"
    with open(tex_path, "w", encoding="utf-8") as fh:
        fh.write(TEX_HEAD.replace("@@CAPTION@@", caption).replace("@@LABEL@@", f"stream-{stem}"))
        for r in rows:
            last = r["nodes"] or r["attack"]
            if r["nodes"] and r["attack"]:
                last = f"{r['nodes']} ({r['attack']})"
            fh.write(" & ".join([
                str(r["seq"]), str(r["round"]), tex_escape(r["mode"]),
                str(r["n_active"]), tex_escape(r["decided_by"]),
                tex_escape(r["type"]), str(r["n_flags"]), str(r["k_votes"]),
                tex_escape(last)]) + r" \\" + "\n")
        fh.write(r"\end{longtable}" + "\n")

    print(f"{stem}: {len(rows)} rows | types {types} | decided_by {dec}")
    print(f"  -> {csv_path}\n  -> {tex_path}")


if __name__ == "__main__":
    main()
